# On MacOS, the tailscale cli is available, but not on the path
if [ -f /Applications/Tailscale.app/Contents/MacOS/Tailscale ]; then
  alias tailscale='/Applications/Tailscale.app/Contents/MacOS/Tailscale'
fi

# Open repo on remote host
repo(){
  target=${1?" Must provide repository name to open on $DEVMACHINE in $DEVROOT"}
  if [ -z "${DEVMACHINE+x}" ]; then error "DEVMACHINE not defined"; fi
  if [ -z "${DEVROOT+x}" ]; then error "DEVROOT not defined"; fi
  code --remote "ssh-remote+$DEVMACHINE" "$DEVROOT/$target"
}
