" Turn off the G-D bell
set visualbell

" Because `YouCompleteMe unavailable: requires UTF-8 encoding. Put the line 'set encoding=utf-8' in your vimrc.`
set encoding=utf-8

" Big red bar at column 81
set textwidth=80
set colorcolumn=+1

" Line numbers
set number
set numberwidth=5

" Enable modelines
set modeline

" for pythoncomplete.vim
"
syntax on
filetype plugin on

" vim-node
set runtimepath^=~/.vim/bundle/node

" turn pathogen on for autoloading plugins in ~/.vim/bundle
runtime bundle/vim-pathogen/autoload/pathogen.vim
execute pathogen#infect()

" vim-markdown
let g:vim_markdown_folding_disabled = 1

