" Turn off the G-D bell
set visualbell

" Because `YouCompleteMe unavailable: requires UTF-8 encoding. Put the line 'set encoding=utf-8' in your vimrc.`
set encoding=utf-8

" Big red bar at column 81
set textwidth=80
set colorcolumn=+1

" Line numbers
set number
set numberwidth=5

" Enable modelines
set modeline

" for pythoncomplete.vim
"
syntax on
filetype plugin on

" tabs vs spaces has been decided
set tabstop=2
set shiftwidth=2
set expandtab

" for particular langauges
autocmd Filetype javascript setlocal shiftwidth=2 tabstop=2
autocmd Filetype html       setlocal shiftwidth=2 tabstop=2
autocmd Filetype python     setlocal shiftwidth=2 softtabstop=2

" vim-node
set runtimepath^=~/.vim/bundle/node

" Turn Pathogen on for autoloading plugins in ~/.vim/bundle, only if it exists
if filereadable(expand("~/.vim/bundle/vim-pathogen/autoload/pathogen.vim"))
    runtime bundle/vim-pathogen/autoload/pathogen.vim
    execute pathogen#infect()
endif

" vim-markdown
let g:vim_markdown_folding_disabled = 1

