
" Big red bar at column 81
set textwidth=80
set colorcolumn=+1

" Line numbers
set number
set numberwidth=5

" Enable modelines
set modeline

" for pythoncomplete.vim
"
syntax on
filetype plugin on

" vim-node
set runtimepath^=~/.vim/bundle/node

" turn pathogen on for autoloading plugins in ~/.vim/bundle
runtime bundle/vim-pathogen/autoload/pathogen.vim
execute pathogen#infect()

