#!/bin/bash
#
# Create /etc/network/interfaces.d/ entry for wireless network

#set -o xtrace

error(){ echo >&2 "`basename $0`: $@"; exit 1; }

wlans=$(dmesg | egrep -o wl[osp][0-9]+ | uniq)
echo "Wireless interfaces found (${#wlans[@]}): ${wlans}"

# only configure the first one we find
(( ${#wlans[@]} < 1 )) && error "No wireless interfaces found"
wlan=${wlans[0]}

# discover and list available wireless networks
ap_table=`mktemp`
trap 'rm -f ${ap_table}' EXIT
sudo iwlist ${wlan} scan \
  | perl -ne '/Signal level=(-?\d+ dBm)/ && print $1." "; /ESSID:(".*")/ && print $1."\n"' \
  | sort \
  | perl -pe '$_ = "$. $_"' \
  > ${ap_table}
cat ${ap_table} # so we can see the list
declare -a "access_points=( `cat ${ap_table} \
                              | perl -ne '/(".*")/ && print "$1 "'` )"
#echo "Found ${#access_points[@]} access points: ${access_points[@]}"

# access point numbers are 1-indexed for humans
while ! (( ap_num > 0 && ap_num <= ${#access_points[@]} ))
do
  read -p "Which wireless network [1-${#access_points[@]}] " ap_num
done
: $(( ap_num-=1 ))
access_point=${access_points[ap_num]}

# generate hashed WPA password with wpa_passphrase
read -s -p "Password for ${access_point//\"/}: "
echo # just a newline
read psk <<< $(echo $REPLY  \
               | wpa_passphrase ${access_point} \
               | awk -F= '/^\s+psk/ { print $2 }' )

# generate the interfaces file for this interface
cat <<EOF >${wlan} 
## THIS FILE WAS AUTOGENERATED BY `readlink -f $0`
# wls34 was detected by `basename $0` from these kernel messages:
`dmesg | egrep wl[osp][0-9]+ | perl -pe '$_ = "# $_"' | xargs -I% echo %`

# the wireless network interface
auto ${wlan}
iface ${wlan} inet dhcp
    wpa-ssid ${access_point}
    wpa-psk ${psk}

EOF

sudo cp -f ${wlan} /etc/network/interfaces.d/${wlan}
